language: java
install: gradle clean
script: gradle check shadowJar
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "RebelliousUno"
  - git config --local user.email "RebelliousUno@Rebellious.Uno"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key: $githubToken
  file: "./build/libs/TwitchBot-*.jar"
  skip_cleanup: true
  on:
    tags: true