language: java
os: linux
dist: bionic

install: ./gradlew clean
jobs:
  include:
    - stage: Check Timezone
      script: timedatectl
    - stage: test
      script: ./gradlew check
    - stage: build
      script: ./gradlew shadowJar
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "RebelliousUno"
  - git config --local user.email "RebelliousUno@Rebellious.Uno"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  token: $githubToken
  file: "./build/libs/TwitchBot-*.jar"
  cleanup: true
  on:
    tags: true